permissions:
  use: "bcheckinv.use"
  change: "bcheckinv.change"

update-interval: 10

inventory:
  size: 54
  title: "&6Инвентарь &7[%player%]"

  slots:
    armor:
      helmet: 0
      chestplate: 1
      leggings: 2
      boots: 3
    hands:
      main: 5
      off: 6
    buttons:
      close: 8
    hotbar-start: 18 # 18-26
    inventory-start: 27 # 27-53

  decoration:
    glass:
      slots: [4,7,9,10,11,12,13,14,15,16,17]
      material: "ORANGE_STAINED_GLASS_PANE"
      name: " "

    close-button:
      material: "BARRIER"
      name: "&cЗакрыть"

messages:
  no-permission-use: "&cУ вас нет прав на использование этой команды!"
  no-permission-change: "&cУ вас нет прав на изменение инвентаря!"
  player-not-found: "&cИгрок не найден или не в сети!"
  usage: "&cИспользование: /invsee <ник игрока>"